---
apiVersion: v1
kind: Service
metadata:
  name: wise-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8081
  selector:
    app: wise-service